### PR TITLE
New Feature: Disable direct autotype

### PR DESCRIPTION
**Pull request by dploeger**
In this PR I implemented a setting to disable the direct run of Autotype if one specific entry can be found.

This is something I need in connection to the feature of specifically entering only the password or username using Autotype.

The default value of this setting is *true*, which mimics the current behavior, so this is backwards compatible and should be valid for a minor version bump.

### CODE REVIEW

**Comment by antelle** [comment]
Hi! Thank 🎁 
Let's change the name of the checkbox, I wouldn't understand what it means. Perhaps should be called something "Directly run auto-type if only one matching entry is found".

**Comment by dploeger** [comment]
Yeah, I was unsure about that as well. Check out my new suggestion.

**Comment by antelle** [comment]
It looks better now!  
Let's hide the setting for web, i.e. where auto-type is not supported. Also please move it to "Function", it doesn't seem to be something general.

**Comment by dploeger** [comment]
You're right. Moved it to function.

**Comment by antelle** [comment]
Thank you! 🎁

**Comment by dploeger** [comment]
@antelle For what release do you plan to include this feature?

**Comment by antelle** [comment]
should be 1.8

**Comment by dploeger** [comment]
Great. 1.8 is released when [these issues](https://github.com/keeweb/keeweb/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.8+no%3Aassignee) are fixed?

**Comment by antelle** [comment]
I haven’t planned it yet, it’s just a quick list of possible issues

**Comment by dploeger** [comment]
Okay, I try to fix some of those if I find the time, because I need this feature.

**Comment by antelle** [comment]
Probably it will take some time to fix them. In theory, we can include this into other hotfixes, or make a new version with auto-type improvements only.

**Comment by dploeger** [comment]
I like that theory. 😆

**Comment by dploeger** [comment]
Maybe include #1128, too.

**Pull request merged**
