### PR TITLE
New feature: Open File from Autotype

### PR DESCRIPTION
**Pull request by dploeger**
This PR adds a shortcut to open a new database from the autotype screen. This somehow completes my workflow on working with multiple databases. 😄

### CODE REVIEW

**Comment by antelle** [comment]
Thanks, merged in https://github.com/keeweb/keeweb/commit/35ed03021a8f0a7903d9594be395772d8f62ca79 (also made some changes there)

**Comment by dploeger** [comment]
@antelle Hm. This seems to work in 1.8, however the hint text is missing on the autotype view.

**Comment by dploeger** [comment]
Thanks btw. 😄

**Comment by antelle** [comment]
You mean the shortcut description? I've removed it intentionally, the shortcut should "just work" as it does on other screens. While other shortcuts are special to auto-type, so we display a hint about it.

**Comment by dploeger** [comment]
Ah, okay. Got it.

**Pull request closed without merging**
