### PR TITLE
[Fix] handle gdrive shortcuts

### LINKED ISSUE #1519: Google Drive Shortcuts Appear in KeeWeb But Cannot be Opened
At least in G Suite, [Google Drive now creates "shortcuts" to files](https://gsuiteupdates.googleblog.com/2020/03/shortcuts-for-google-drive.html), rather than allowing you to add them directly to your My Drive. These shortcuts show up as password databases in KeeWeb, but attempting to open a shortcut results in a 403 error (some of my users have also reported 400 errors, but I've only been able to reproduce 403 errors).

Attempting to open the original database works fine.

Steps to reproduce:

1. In Google Drive, right-click on a known good KDBX file and choose "Add shortcut to Drive".
2. Add the shortcut to a folder that your original file isn't in (to make it easy to find).
3. In KeeWeb, open a new file from Google Drive and navigate to the folder you added the shortcut to. Observe that the shortcut shows up as a valid password database.
4. Click on the shortcut file, enter the database password, and hit Enter.
5. 403 error (or maybe, as noted above, 400).

### PR DESCRIPTION
**Pull request by Nu11u5**
Fixes #1519

In the event that a file is a shortcut, uses the targetId instead of the file id.
No headRevisionId is initially available, but the existing behavior will retrieve it from the target when stat() is called.

### CODE REVIEW

**Comment by Nu11u5** [comment]
If this qualifies as a bugfix I can rebase it from master.

**Comment by rjt** [comment]
@Nu11u5 Looking forward to testing whether this pr helps keeweb work with gSuite Google Workplace SharedDrives?

**Comment by Nu11u5** [comment]
> @Nu11u5 Looking forward to testing whether this pr helps keeweb work with gSuite Google Workplace SharedDrives?

Unfortunately the developer is no longer maintaining this project, and has not handed it off to someone else.

**Comment by Aetherinox** [comment]
This will be reviewed and planned to be integrated as part of the next v1.19 update:
- https://github.com/keeweb/keeweb/pull/2168

**Comment by Nu11u5** [comment]
> This will be reviewed and planned to be integrated as part of the next v1.19 update:
> 
> * [v1.19 Updates #2168](https://github.com/keeweb/keeweb/pull/2168)

Thanks @Aetherinox I'm very glad to see this project becoming active again.

**Pull request merged**
