### PR TITLE
Replace the bower dependencies with NPM dependencies

### PR DESCRIPTION
**Pull request by twang2218**
This PR will replace the `bower` dependencies with NPM dependencies.

TODO:
- [x] `jsqrcode`: I didn't find this package on NPM so use GitHub repo instead for now.
- [x] `argon2-browser`: I did find this package on NPM, ~however, it's outdated, so I'm using `1.1.0` for now, I have raised the issue on `argon2-browser` repo, https://github.com/antelle/argon2-browser/issues/10.~ Now using `1.3.0`.

### CODE REVIEW

**Comment by antelle** [comment]
Hi! Thanks for this, I've updated `argon2`. That's ok to use `jsqrcode` from github, since we're using customized fork. I'm not sure if it makes sense to push it to npm, probably not.

**Comment by antelle** [comment]
🎁

**Comment by twang2218** [comment]
Ok, updated `argon2-browser` version to `1.3.0`.

I found `package-lock.json` is always changing, maybe `yarn` will be better.

**Comment by antelle** [comment]
Thanks! Merged it. 🎁

**Pull request merged**
