### PR TITLE
Bump electron to 13

### LINKED ISSUE #1975: Crash on launch: GPU process isn't usable
**Describe the bug**
App crashes on launch without showing any graphical interface

**To Reproduce**
```bash
➜  ~ keeweb                                         
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[39809:0127/140651.852037:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
[1]    39809 trace trap (core dumped)  keeweb
```

**Expected behavior**
App starts

**Environment**
KeeWeb v1.18.7 (dfc6201, 2021-07-18)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.7 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

Linux fedora 5.15.15-200.fc35.x86_64

**Notes**

This seems to be fixed starting with electron v13.5.0 (https://github.com/electron/electron/pull/31091)

Workaround by adding `--no-sandbox` to launch options: `keeweb --no-sandbox`
On Fedora 35, you can edit the desktop launch entry at `/usr/share/applications/keeweb.desktop`

### PR DESCRIPTION
**Pull request by HarlemSquirrel**
I was able to successfully run this on ArchLinux with

```
npm install electron@13

npm run dev-desktop-linux

tmp/desktop/keeweb-linux-x64/keeweb
```

Closes #1975

### CODE REVIEW

**Comment by Jule-** [comment]
Could this PR be integrated to have something working again?

**Comment by segux** [comment]
Can be this PR Merged ASAP? Right now we're forcing to use --no-sandbox to make it works.

Thanks in advance

**Comment by AlexWayfer** [comment]
> Can be this PR Merged ASAP? Right now we're forcing to use --no-sandbox to make it works.
> 
> Thanks in advance

@antelle has kind of year-long inactivity, and I doubt that there are other active members/maintainers.

**Comment by Jule-** [comment]
As a workaround, you can use `--in-process-gpu` flag, as mentioned here: https://github.com/keeweb/keeweb/issues/1975#issuecomment-1323377309

**Comment by Jurrie** [comment]
FYI: In https://github.com/keeweb/keeweb/issues/2072#issuecomment-1545331928 I posted another solution which worked for me, and seems to work for other people as well.

**Comment by Aetherinox** [comment]
Looks like for now, everything is at a stand-still.
Going to do patches for my own copy and work on adding passkey integration. If the dev comes back, I can add a pull.

**Comment by KaKi87** [comment]
Hi @Aetherinox,
I see that you're still maintaining your fork, and that the original KeeWeb maintainer won't come back anytime soon,
Would you then be open to enabling issues ?
Thanks

**Comment by Aetherinox** [comment]
@KaKi87 Yeah I'd be alright with that. I'm just updating a few of my other scripts this week and I've been spending this time getting used to the structure of KeeWeb.

I had to initially add a few features that I myself needed, and I've been occasionally glancing over at this issues section and chopping the list down of things.

**Comment by KaKi87** [comment]
Thanks, in the meantime I'll repost my feature requests.

**Comment by Aetherinox** [comment]
I just configured all of my automated scripts for the repo. As soon as I turned dependabot on and did triage, I realized I have my work cut out for me. 

There's a lot of outdated packages, with a lot of security vulnerabilities I have to work through. Especially bad for a program that is supposed to be storing confidential information. Granted, it's offline; it still needs addressed, asap.

**Comment by Harald-Koschinski** [comment]
> I just configured all of my automated scripts for the repo. As soon as I turned dependabot on and did triage, I realized I have my work cut out for me.
> 
Will you come the maintainer of this project? That would be really great.

**Comment by KaKi87** [comment]
They're maintaining their fork of the project, not the original repo of the project.

Even if they asked, I don't think the original creator would be there to respond right now.

**Comment by Aetherinox** [comment]
@Harald-Koschinski 

I'm maintaining my own repo of the program now. The owner has been MIA for quite awhile, and I've already invested time into adding some features I needed.

Right now the current plan is that I'm going through all of the packages which have massive security vulnerabilities and I'm slowing going through and updating the packages to a more recent version; ensuring that all functionality still works after each update. A few of them are so old, the syntax and library itself has completely changed; so I'm having to slowly go through and replace old methods and classes with new.

**Comment by Harald-Koschinski** [comment]
> @Harald-Koschinski
> 
> I'm maintaining my own repo of the program now. The owner has been MIA for quite awhile, and I've already invested time into adding some features I needed.
> 
> Right now the current plan is that I'm going through all of the packages which have massive security vulnerabilities and updating the packages to a more recent version; ensuring that all functionality still works after each update. A few of them are so old, the syntax and library itself has completely changed; so I'm having to slowly go through and replace old methods and classes with new.
> 
> This PR is talking about Electron 13, which is over 2 years old. Whereas another project I manage is on Electron 29, and there have been a lot of optimizations and added features in that time I'd like to use.
> 
> And changing a few things up, because I develop differently than how this program was configured. Just getting used to the structure and making it comfortable to work with.

That's really good to hear. Keeweb is a really great program I love and use constantly.
I did not know that the original maintainer is completely not responding. So your stragedy is the only and good way to go.
I wish you success and hope to see a new release soon.

**Comment by Aetherinox** [comment]
Appreciate it. Feel free to [star it](https://github.com/Aetherinox/KeeWeb) and check back some time. I'm hoping with a good month of work, it can get a significant boost to make up for lost time.

I've had to update a few other projects but I'll have a lot of time after to focus on keeweb. Just have to make sure I don't neglect my other stuff too.

**Comment by Harald-Koschinski** [comment]
The website https://keeweb.info/ with the old stuff is also a problem to solve.

> Appreciate it. Feel free to [star it](https://github.com/Aetherinox/KeeWeb) and check back some time. I'm hoping with a good month of work, it can get a significant boost to make up for lost time.
> 
> I've had to update a few other projects but I'll have a lot of time after to focus on keeweb. Just have to make sure I don't neglect my other stuff too.

The website https://keeweb.info/ with the old stuff is also a problem to solve.

**Comment by Aetherinox** [comment]
Definitely something I've been tumbling around in the back of my head.

Also the fact that I'm going to have to put out approx. $200 to get a certificate that has been signed by a Certificate Authority so that the software can run without windows warning of an untrusted publisher.

**Comment by KaKi87** [comment]
> I'm going to have to put out approx. $200 to get a certificate that has been signed by a Certificate Authority so that the software can run without windows warning of an untrusted publisher.
>
> At present, I use a self-signed certificate, which is fine for tiny projects, but probably not a good idea with KeeWeb.

I disagree : you should not do that.

It doesn't matter that the certificate is self-signed, what matters is that it's verifiable from your repo.

**Comment by Aetherinox** [comment]
> > I'm going to have to put out approx. $200 to get a certificate that has been signed by a Certificate Authority so that the software can run without windows warning of an untrusted publisher.
> > At present, I use a self-signed certificate, which is fine for tiny projects, but probably not a good idea with KeeWeb.
> 
> I disagree : you should not do that.
> 
> It doesn't matter that the certificate is self-signed, what matters is that it's verifiable from your repo.

It probably won't matter at the beginning in terms of a self-signed vs having a CA; but I think it could be an issue in the future. Even if the self-signed returns to my repo, some people are just....very strict on that type of stuff. Makes them feel uneasy to ignore that aspect.

For now, probably not high on my list, but it's something to address somewhere in the future, right now I've got more important tasks that need addressing.

**Comment by KaKi87** [comment]
> some people are just....very strict on that type of stuff

That's the kind of people who'd rather use proprietary stuff like Dashlane or at least something with a back-end like Bitwarden, so please don't bother.

This is a free and open source project, you're not supposed to spend such a sum on it like that.

**Comment by KaKi87** [comment]
If there were really interested in their safety, they'd just build from source.

**Comment by antelle** [comment]
Hi! I don’t have time to support the repo anymore, but I can help you to transfer the domain keeweb.info and if you decide who would like to maintain the repo, add collaborators, if you wish.

**Comment by KaKi87** [comment]
Hi @antelle,
I think @Aetherinox would be interested.
So, what are you using instead of KeeWeb nowadays ?
Personally I couldn't be satisfied with anything else so I kept using it.

**Comment by Aetherinox** [comment]
@antelle Welcome back to the land of the living. Hope all is well IRL. Your choice of maintainer is really up to you. I've been getting into it as I have spare time as I've had a few other updates to push. 

But I definitely don't want to see KW go into the abyss, as I've used it for a long time, and there's a mountain of things that can make it even better. However, I'm down for others contributing as well.

**Comment by HarlemSquirrel** [comment]
I am happy to collaborate and help maintain. I primarily use KeeWeb on Linux including Ubuntu/Pop_OS and Arch Linux but also occasional on Windows.

**Comment by Aetherinox** [comment]
We're going to have to hunt down a few for mac. I do Ubuntu / Debian and Windows. Hadn't had an apple product in ages.

**Comment by KaKi87** [comment]
I wouldn't mind dropping Apple support altogether, considering the closed environment that it is.

But if you really want to support Mac, then there's sosumi.

**Comment by Aetherinox** [comment]
I honestly wouldn't mind dropping apple because it's just a pain in the rear to deal with them, but personally I just don't see that as a good thing to do to existing users. I'd support them as long as I can, but I agree, apple is a pain to deal with.

**Comment by KaKi87** [comment]
> I just don't see that as a good thing to do to existing users.

Existing users are technically already stuck like Linux and Windows users so it won't change anything.

> There are a few software titles on Windows I need which cannot run on Linux

If you don't do gaming nor multimedia editing then you could use a VM.

Personally I fully moved to Linux Mint but I still (and probably always will) have a VM for Paint.NET and Adobe Acrobat.

**Comment by antelle** [comment]
@Aetherinox thanks, I’m good, actually even too good, to be able find time for doing anything meaningful outside of my job, like I did before. 

@KaKi87 I’m using one of alternatives listed here in a wiki page, that has good integration with iPhone and mac.

@Aetherinox @HarlemSquirrel, if you would like to be included here as a contributor / maintainer, let me know. Maybe there will be some sort of community effort, we’ll see how it will go.

I tried to find a maintainer and received only requests for providing occasional help with some features and merge requests, while there’s also maintenance work that needs to be done: CI, website updates, releases, and so on. So far I couldn’t find anyone who would be interested.

While the project was active, there was some budget collected, so if anyone wants to purchase a cerificate Apple or Microsoft, you are welcome to do so for free. You can submit an expense here: https://opencollective.com/keeweb/, I believe it should be more than enough for years of development.

The challenges that I see:
- Windows build requires a USB dongle, which adds some fun to the build process and a maintainer who would spend some time during build
- Supporting all this in CI is not a piece of cake
- Apple does have some custom modules in auto-type and touch-is, but they work as-is, unless you would like to add new API like fingerprint unlock
- Hosting needs to be moved to CloudFlare pages with releases downloadable from GitHub, most likely, now it’s on my GCP
- The framework in KeeWeb is old, I started migrating it to React, but did’t have time to finish
- KeeWeb as iOS webapp doesn’t work without Password Manager API, maybe it’s worth rebuilding with Electron native, if someone would like to have an iOS app of course (the problem is only on iOS and probably on Android, for mac it works amazing)
- project direction, triaging issues, priorities and planning need alignment if we want to have a coherent experience and design

I’m ready to assist anyone with infrequent advice, knowledge sharing and so on.

**Comment by Aetherinox** [comment]
@antelle Good to hear. After the news of Bram Moolenaar passing away; I've had enough news for the next 10 years. So as long as you're doing good.

In regards to development; I'd definitely be interested. And I do agree with the react migration, would definitely benefit from a framework upgrade. 

My only main concern is keeping Apple support going. I have plenty of test environments for Windows, Linux, and Android, but I have absolutely nothing apple related. But where there's a will, there's a way. So if worst-case comes; I'll look into obtaining an apple environment to work with.

Code-signing shouldn't be an issue, as I often sign my binaries, including a dongle, and I also sign using my Yubikey with a certificate imported. The downside is that I've never had the need to buy a certificate from a CA, because a lot of my stuff is open-source, and I never saw it as a huge deal unless one of my projects were to explode in usage and the topic were brought up by a user; so I've been signing with a self-signed certificate for binaries, and GPG for hashes / commits.

**Comment by antelle** [comment]
@Aetherinox ok I’ll add you to the project.

The certificate from Certum for Windows is €70 per year, the others are  €200..300 a year which should be fine since there’s about €2000 collected, but they require a validated company name. A USB dongle is fine if you sign it locally. With CI, it becomes harder when you can’t export a certificate anywhere and you don’t have a DC where you can plug in that device.

**Comment by antelle** [comment]
Just sent you an invite. To my knowledge they all try to enforce their own dongles, but maybe things have changed and now they allow YubiKeys. For EV there may be more flexible options, but I assume EV code signing is not what we can afford.

**Comment by Aetherinox** [comment]
Thanks.

Yeah I'll look through tonight and see what the options are. Definitely don't want to go spending more than is really needed. But I need to understand the options first before picking a route. 

In a perfect world; they'll accept Yubikey with FIPS, and then just have a cert signed. Digicert seems to offer a PKI client which allows you to plug in a Yubikey and import your certificate, but I need to see the specifics.

**Comment by HarlemSquirrel** [comment]
I'm happy to come on as a maintainer as well. I'm not familiar with building with a USB dongle but I have lots of experience with CI workflows. 

I do have a MacBook from my full time job that I might be able to use for testing or builds.

**Comment by HarlemSquirrel** [comment]
Do we need to be concerned about different VPU architectures like with MacOS on Intel vs M1, M2, M3?

**Comment by antelle** [comment]
Invite sent. Yea the CI builds both Intel and Apple Silicon. For Apple there’s mo dongle required, everything is built on CI. You need to accept new terms and conditions from time to time though…

**Comment by HarlemSquirrel** [comment]
How do we feel about this PR to bump the electron version? Can I get an approval?

**Comment by Aetherinox** [comment]
@antelle Never thought I'd spend 3 hours on a token / signing class.

So Certum offers the open-source package, the "Set" package if I understand correctly, includes the USB token, the card reader, and then your cert.

After the first year, the price goes down to just the cost of renewal, if I'm understanding correctly.

In terms of Yubikey, yes, some companies allow you to use a Yubikey. You'd generate your key, send in the CSR / attestation, get it signed, and then once you get the file back; you now have a trusted signing key. This works for companies like Secitgo and Digicert.

However, Certum uses their own key they send. And it seems that with Certum being priced at $80 or so (give or take tax), it's still a cheaper price to get the device and cert from them, than it would be to go with Secitgo, because some of their prices seem way above what Certum charges. 

I don't know the legality behind what they allow as far as an open-source program. KeeWeb is open source, but it also takes in donations / backers; and I haven't checked if Certum still considers that as a qualifier. Certain companies I've seen will allow open-source backers, but it must not exceed a certain amount; so I assume you would have the answer to that.

**Comment by antelle** [comment]
@HarlemSquirrel I assume you can merge it without an approval, since you have write access now.

@Aetherinox Certum doesn’t have any statement about donations, it is legal.

**Comment by Aetherinox** [comment]
@HarlemSquirrel I'm about 99% sure there's no issues because I seem to recall this being one of the first bumps I did on mine, but did you run through real quick with the app just to make double sure it didn't cause issues.

**Comment by HarlemSquirrel** [comment]
I just opened it and viewed my vault.

**Comment by KaKi87** [comment]
How about directly trying to upgrade to v29 ? I bet it wouldn't be easy, but then you'd only have to do it every 2-6 months (the faster the less effort it will require).

**Comment by Aetherinox** [comment]
We can push @HarlemSquirrel's push for now, I'm just testing to ensure everything functions, and then work on a more recent version. I know for a fact that v29 is going to require a bit of work.  I use that for a few of my projects, and there have been quite a few major changes between then and now.

But sometime soon, I want to sort of get a game-plan together with a direct route for our objectives so we have a path to follow. Right now we're just doing minor updates to catch a few things up, but I like the original goal @antelle had with migrating to the react framework.

**Review by Aetherinox — APPROVED** [review]
No conflicts found.

**Comment by Aetherinox** [comment]
@antelle Two points / questions. And sorry, don't want to bug you because I know you have IRL stuff going on, and that was the point of bringing in help.

1. You have the access to Microsoft Azure / client / secrets, referenced here: https://github.com/keeweb/keeweb/pull/2062. They offered just a rough patch to bypass it, but since you have access, it may be easier that way.

2. Us creating teams in the organization, or some type of way to communicate amongst one another, so we're not dropping random messages in various different PRs. It shows me that I can create a team, but I wanted to confirm with you first before I go doing things like that.

**Comment by antelle** [comment]
@Aetherinox you can ask me of course, it’s fine, I can just be slow to answer. I think I know the problem, I’vd deleted that old Microsoft account because it had different issues with it, so the Azure application is also lost.

**Comment by Aetherinox** [comment]
@antelle Yeah I figured it was probably either an expired secret, or gone. I went through and took a look at Azure on my end, but I haven't studied it enough to know the redirect URLs. 

It also looks like you might have encoded the secret id, for some reason, mine didn't have the same format as yours, character wise. But I was able to gen the secret and client id fine just to poke around and see how it worked.

**Comment by antelle** [comment]
It’s not encoded, before Azure generated ids that way so for my setup it continued to be like that. I could not create a new application in that account, somehow it was broken in a weird way.

**Comment by antelle** [comment]
Regarding your question above about teams yes why not, since there are more contributors now, it would make things easier

**Comment by HarlemSquirrel** [comment]
I could also be helpful to create a GitHub project where we could track some issues on a Kanban board

**Comment by Aetherinox** [comment]
Yeah, project board would help, I often use them to organize and triage.

I didn't get much sleep apparently, I thought "Oh yeah, a project board". Then I went to the home page for the repo and sat there for a good 45 seconds going "Why don't I see settings". Realizing I'm not on my own repos lol.

**Comment by antelle** [comment]
@Aetherinox @Harald-Koschinski made you both owners of the org, it looks like you can't manage projects, boards, etc... on GitHub and we can't create roles on a non-enterprise plan

**Comment by Aetherinox** [comment]
I haven't looked into the policies for Github lately, but I'm shocked that last time I read; Github didn't have an open-source plan which allowed open-source projects to take advantage of those features.

That's the one reason I give Gitlab credit; they've got a few programs in place for open-source that are nice.

**Comment by KaKi87** [comment]
Would you consider Codeberg, which is running Forgejo, an alternative to GitHub and GitLab that is 100% FOSS and more lightweight ?

**Comment by antelle** [comment]
I don't think there's a point tbh. Any opensource org will need a few owners anyway when it's maintained by several people and for the rest of contributors write permissions should be okay.

**Comment by Aetherinox** [comment]
I just checked out Codeberg, and I swear, it looks like a fork of Gog / Gitea. But it does seem pretty limited. 

I have an obsession with workflows. I create them for everything just so I can focus on other things and let the system do the dirty work.

**Comment by KaKi87** [comment]
> I just checked out Codeberg, and I swear, it looks like a fork of Gog / Gitea.

Codeberg runs Forgejo, which is a fork of Gitea, which is a fork of Gogs.

> But it does seem pretty limited.

How so ?

**Comment by Aetherinox** [comment]
@antelle My brain didn't even register, thanks for ownership perms. lol. I went back to the repo and noticed settings now.

@KaKi87 Ah ok, that explains the similarities. I remember the drama with Gogs, and Gitea being branched off Gogs due to some concerns some of the maintainers had. I'd say moreso just "not feature rich".

I run a Gitea install on a VPS that I use for internal development, so it probably has all the same features of Gitea, Depending on how caught up Codeberg is; Gitea was attempting to implement features such as merge queues, and also a solution for "Github Pages" for Gitea. There was a solution but it was an external library that wasn't directly integrated into the software; it was supported by a 3rd party developer. Also SAML 2.0.

I'm probably a few versions behind on Gitea now, so I haven't been keeping super close track of recently implementations.

**Comment by Aetherinox** [comment]
@antelle One more Q for today. Do you mind if I add a few more labels so I can mark the status of things. I like labels to keep track so I can go back and search later.

Don't want to go changing things up unless you're alright with some tweaks.

**Comment by antelle** [comment]
I don’t mind, of course, feel free to configure the labels

**Comment by KaKi87** [comment]
> I'd say moreso just "not feature rich".

Well, I'm surprised, since I'm the kind of person who doesn't switch to open source alternatives unless they're at the same level as the proprietary app, which I felt Forgejo was.

The community is pretty active, so if you're missing something, then please make requests.

> merge queues

I don't know what that is.

> "Github Pages" for Gitea. There was a solution but it was an external library that wasn't directly integrated into the software

That's [Codeberg Pages](https://codeberg.page/).

> SAML 2.0

I don't know what that is either.

> tabbed system for the most popular repo files, such as the ability to pick a license

I don't know what you mean by "tabbed system", but the ability to pick a license exist, as well as a gitignore, or even use template repositories.

**Comment by Aetherinox** [comment]
Merge queues are basically the solution for high-traffic repos where you have a large number of people committing / pulling each day. The CI creates a temp branch which has the original code, all code changes from any other PR which deals with that set of files, and then your pull request. It works out the issue of having merge conflicts with other merges.

In your repo, you can enable branch protection and then toggle `Require status checks to pass before merging `.

SAML 2.0 = Single Sign on 2.0 for organizations

For the tabbed system, and the other QOL features I was looking for, I'll just link my feature requests; that best explains it.
- https://github.com/go-gitea/gitea/issues/27328  (Tabs)
- https://github.com/go-gitea/gitea/issues/27308

**Comment by Aetherinox** [comment]
@antelle I lied, sorry. One more question. Do we have a link to our ToS available on the website's official domain like we do the privacy policy such as: https://keeweb.info/terms.html

**Comment by antelle** [comment]
Both ToS and PP yes:

https://keeweb.info/terms-of-use.html
https://keeweb.info/privacy-policy.html

**Comment by SethFalco** [comment]
Hey hey!

Just thought I'd drop a message for the others that joined the org, as before I was aware of the activity here, I had already emailed the author of the project.

I was invited to the org too and have triage permissions. I only expect to give 1-2 days a month, and aim to help with triaging issues, reviewing pull requests, and fixing reproducible bugs reported. In other words, I don't have the capacity to help define the project's direction or how it evolves right now, but I'll certainly do my best to support it while addressing the backlog.

**Comment by Aetherinox** [comment]
I'll let this be reviewed by antellle. Even though we're owners in the org, he's still project owner.

I don't have any issue with it. My only ask is that with PRs, things be fully tested before a merge. At present, before I merge a PR, I test to make sure any aspect of that code cannot break another feature. 

As an example, there is a PR to address MS Teams, but the PR attempts to re-route OneDrive credentials for use with MSTeams, and it also ignores a few things and is really just a slap patch, and I'd like to properly patch things. Minus the fact that the PR doesn't even work now because the system has changed.

**Comment by KaKi87** [comment]
Hi @Aetherinox, how's your to-do list going ? Thanks

**Comment by Aetherinox** [comment]
It's progressing, I'm just up to my eyeballs in code. Right now getting our new worker set up so that we can bring the favicon downloader back online.

**Comment by KaKi87** [comment]
Alright, would you mind putting the list into an issue so that we can follow the progress ?

Thanks

**Comment by Aetherinox** [comment]
Did you check the discussion section? Usually about every 4-6 days, I post an update.
- https://github.com/keeweb/keeweb/discussions/2154

Toward the bottom of that top post.

**Pull request merged**
