### PR TITLE
added teams storage; added tenant id configuration for microsot

### PR DESCRIPTION
**Pull request by saulobejo**
- added teams storage
- added tenant id configuration for onedrive and teams

The code was tested to browse and open. Haven't tested to write.

Linked to issue #1265 

Adds new requirements to the Azure Active Directory Configuration:
- Permission:
  - Sites.ReadWrite.All
  - Team.ReadBasic.All
- Redirect URL:
  - https://HOSTNAME/oauth-result/teams.html (MUST ALSO BE ADDED TO THE SHARED TENANT)

Known issues:
- not able to return to the list of Teams
- Code could be merged with onedrive once the API is the same but would need some abstraction.

### CODE REVIEW

**Comment by antelle** [comment]
Hi! Thank you, I think "teams" should be renamed to "Microsoft Teams" because it's not a product name, but rather a word that can be used for example by Google as well.

> Haven't tested to write.

It should be very easy to test: open a file from this storage, change anything, and save it back.

For future testing: does it need any special account for development, can it be tested with personal OneDrive?

**Comment by saulobejo** [comment]
@antelle  would msteams be acceptable?

**Comment by antelle** [comment]
In the code doesn't matter, I mean more what is displayed in the UI. Probably "Microsoft Teams" would look better there, what do you think?

**Comment by saulobejo** [comment]
@antelle it fits nicely in the UI. rename committed

I've tested writing and it worked great.

I can't test using regular OneDrive account until you add the teams' oauth webpage as a valid return url in your azure application.

**Comment by antelle** [comment]
I also renamed some constants: https://github.com/keeweb/keeweb/commit/674ed2cc729cd10dc76455fc11e684d367f1f40b and made it disabled by default

**Comment by antelle** [comment]
Will make a release with it soon because 2.0 won't happen this summer most likely. Thank you! 🎁

**Comment by saulobejo** [comment]
thank you very much @antelle !

**Comment by antelle** [comment]
Do I need something special in the Microsoft OAuth app setup, or it can't be done at all for Teams, like we have for OneDrive?

**Comment by saulobejo** [comment]
@antelle 

for the oauth you need to add `https://HOSTNAME/oauth-result/msteams.html` as a valid return URL.
Also, the manual needs to be updated to add the new permissions `Sites.ReadWrite.All` and `Team.ReadBasic.All`

**Comment by saulobejo** [comment]
Getting this error when trying to connect to my private Teams using your client id (`b97c53d5-db5b-4124-aab9-d39195293815`). Probably because of the return URL.

image

**Comment by antelle** [comment]
Yes, I need to create a new client for teams as far as I understand. Will do it next week

**Comment by antelle** [comment]
Created a client, here's its id: `8fbe2245-13d5-446f-bedc-74c3b2e1f635`

**Comment by saulobejo** [comment]
@antelle onedrive has 2 clients.

one for dev and one for prod/desktop with the later requiring a secret.

https://github.com/keeweb/keeweb/blob/1d61c6ca03e4c2d489d7c01f48bbd7d9ee6a3da5/app/scripts/const/cloud-storage-apps.js#L27-L38

which one is this one?

**Comment by antelle** [comment]
None of them, I've added a new one for Teams: https://github.com/keeweb/keeweb/commit/3b49562f64d5d9aa838f33c49f03be83149c85b7

**Comment by saulobejo** [comment]
@antelle  worked like a charm!

**Comment by antelle** [comment]
Ok, thanks for testing, I'll merge it this week and make a release with it.

**Comment by sauloal** [comment]
Hello @antelle .
So you have an ETA for the next release containing the MSTeams feature?
Regards and thanks

**Comment by antelle** [comment]
I was going to release it today if everything goes well.

**Comment by sauloal** [comment]
Fantastic! Thanks a lot

**Comment by antelle** [comment]
Done: https://github.com/keeweb/keeweb/releases/latest

**Comment by saulobejo** [comment]
Screenshot_20210719-080310

Getting an error when trying to use teams in your public instance.
The private instance works well.

**Comment by antelle** [comment]
Can you please capture the redirect uri from parameters? I have `https://app.keeweb.info/oauth-result/teams.html` there, but it doesn't seem to work.

**Comment by sauloal** [comment]
it should be msteams.html for starters. ill  try later

**Comment by antelle** [comment]
Indeed thanks, fixed that

**Pull request merged**
